services:
  db:
    environment:
      - POSTGRES_DB=nextjs
      - POSTGRES_USER=nextjs
      - POSTGRES_PASSWORD=nextjs
    image: postgres
    ports:
      - 5432:5432
  adminer:
    image: adminer
    ports:
      - 8080:8080
